---
- name: Display and Delete Inactive Users
  hosts: servers
  vars_files:
   - veriable.yaml
  become: true

  tasks:
    - name: Display inactive users
      shell: lastlog -b "{{ day }}" | awk '! /root/ && NR>1' | awk '! /Never logged in/ && NR>1 {print $1}'
      register: inactive_user_dirs
      ignore_errors: yes  # Ignore errors in case some directories are not found

    - name: Parse inactive user directories
      set_fact:
        inactive_users: "{{ inactive_user_dirs.stdout_lines | map('basename') | list }}"
      when: inactive_user_dirs.rc == 0

    - name: Print inactive users
      debug:
        var: inactive_users

    - name: Remove apache config files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/httpd/conf.d/{{ inactive_user_dirs.stdout }}-app-bigcommerce.conf
        - /etc/httpd/conf.d/{{ inactive_user_dirs.stdout }}-services.conf
        - /etc/httpd/conf.d/{{ inactive_user_dirs.stdout }}.conf
        - /etc/httpd/conf.d/stickyio-{{ inactive_user_dirs.stdout }}.conf

    - name: Delete inactive users
      user:
        name: "{{ item }}"
        state: absent
        remove: true
      loop: "{{ inactive_users }}"
      when: inactive_user_dirs.rc == 0

    - name: Restart Apache service
      service:
        name: httpd
        state: reloaded
        enabled: yes
    - name: Check status of the service
      command: service httpd status
      register: result
    - name: showing Service status
      debug:
       var: result.stdout
    
    - name: Home folder gzip create
      archive:
        path: /home
        dest: /var/home.tar.gz
    - name: Copy the compressed archive
      synchronize:
        src: /var/home.tar.gz
        dest: /home/ubuntu
        mode: pull
      delegate_to: ubuntu@171.31.33.70
